### PR TITLE
Add document and picture uploads

### LINKED ISSUE #53: Allow document and picture uploads on offer applications
### Motivation

Part of the MVP

### User Story

As an offer provider, I want to provide additional information on offers in the form of documents. I also want to be able to set a representative offer picture.

### Proposed Solution

- add possibility to upload files in the offer form
- add possibility to upload a single offer photo in the offer form

### Additional Context

- we should probably set a default image in case none is uploaded
- the Figma designs show neither of the two upload forms, but they are clearly required. Maybe we could use this opportunity to rearrange some of the form sections of the offer form into something more sensible as well
- blocked by #37

### Screenshots

Not shown in any of the Figma designs

### PR DESCRIPTION
**Pull request by charludo**
### Short description

Add document and picture uploads to the offer application/edit

### Proposed changes

- the title image is a new field on the offer_version. We could also discuss moving this to the offer at a later point
- documents are uploaded via a new `DocumentUploadForm`
- I had a look at dropzone for sending the files via ajax, but decided it was probably too much work for the MVP. If we want to, we can still swap out the custom form for Dropzone at a later point, but I think the current solution is more than enough for now.

### Side effects

- from a user standpoint: I dislike how imbalanced the two columns of the form are becoming. Maybe we should move some parts to the right column, for example the location and group mode fields would make sense IMO - have offer-specific details to the left, organisational details (who/where/how) to the right.

### Resolved issues

Fixes: #53

### CODE REVIEW

**Review by svenseeberg — APPROVED** [review]
The changes look good so far. Saving the form is not possible right now, I get the following message:
```
An invalid form control with name='location-lat' is not focusable. <input type=​"number" name=​"location-lat" step=​"0.000001" placeholder=​"Enter latitude here" required id=​"id_location-lat">​
```

But this is also the case with the current develop branch and could therefore be solved with another PR?

**Comment by charludo** [comment]
> The changes look good so far. Saving the form is not possible right now, I get the following message:
> 
> ```
> An invalid form control with name='location-lat' is not focusable. <input type=​"number" name=​"location-lat" step=​"0.000001" placeholder=​"Enter latitude here" required id=​"id_location-lat">​
> ```
> 
> But this is also the case with the current develop branch and could therefore be solved with another PR?

Are you trying to create an online-only offer? If so, this is pribably related to #72. Otherwise, could you tell me how to reproduce this?

**Comment by svenseeberg** [comment]
> Are you trying to create an online-only offer? If so, this is pribably related to #72. Otherwise, could you tell me how to reproduce this?

I cannot submit the form, no matter what I do :grimacing: I also tried different browsers. But yes, it seems to be this issue.

**Comment by charludo** [comment]
> I cannot submit the form, no matter what I do grimacing I also tried different browsers. But yes, it seems to be this issue.

Ah, no, it's the bug that will be fixed in #66. If you un-hide the coordinate input fields you cna see the warning about overprecise coordinates.

**Review by JoeyStk — APPROVED** [review]
I also got the same error with the over-precise coordinates. Except for it, it worked as expected. Thank you! :rocket:

**Pull request merged**
