### PR TITLE
Add Integreat CI to the compass

### LINKED ISSUE #74: Rework design to match the Integreat CI
### Motivation
Since the project has been rebranded from Integrationskompass to Integreat-Kompass we need to make some adjustments to the UI to match the CI of Integreat.

### User Story
As a project owner I want the user to have a subconscious connection to Integreat so that they also find other related products/assistance.

### Proposed Solution
Follow the new guidelines defined by the UI/UX team in Figma

### Alternatives
None

### Additional Context
There is already some work on this in progress, but as for now this issue is still blocked by UI/UX

### Screenshots
Screenshot for: All offers
grafik

(More screenshots coming as work on this progresses)

### PR DESCRIPTION
**Pull request by JoeyStk**
### Short description

This PR changes the design so it fits the CI of Integreat. Please checkout the mockup in our [design file](https://www.figma.com/file/HciesfV03nJCvq2jaepF4o/Integrationskompass?type=design&node-id=1221%3A103333&mode=design&t=ENgpHw9eQpkjRjq6-1).

### Proposed changes

- Changing a few of the translations
- Changing mostly CSS classes
- Changing the primary color in the tailwind config and adding a secondary and tertiary color to it

### Side effects

- This PR is now ready for review

### Resolved issues

Fixes: #74

### CODE REVIEW

**Comment by amikable-tech** [comment]
The details icon is missing in the bottom right corner of the offers. Please see attached what we have in the mock up design
Screenshot from 2023-09-04 15-33-03
Screenshot from 2023-09-04 15-35-05

**Comment by charludo** [comment]
Wow, looks fantastic already!!
Do we have new desigts for the logo and favicon already, btw?

**Comment by JoeyStk** [comment]
> Do we have new desigts for the logo and favicon already, btw?

Yes, and they also should be implemented. If they are not applied yet on your local machine, you might have to restart the server. That fixed the issue for me

**Comment by JoeyStk** [comment]
> The details icon is missing in the bottom right corner of the offers. Please see attached what we have in the mock up design

Good catch! I asked UI/UX about it, and will get to you as soon as I hear from them

**Review by charludo — CHANGES_REQUESTED** [review]
Fantastic!! Thank both you and @IsabellaTG so much, this looks great.

A couple things I noticed:
- the white text on yellow buttons is barely legible. I'd suggest changing it to text-gray-700 everywhere, same as on the tags
- speaking of which, they (and the mode switches) also still have white text in the offer application form
- same for the range filter
- hovering over login/register, the text is too dark, it should be white/yellow respectively IMO
-  and while not reletated, I notced that the help text in the report form is misaligned, could you fix that with this PR as well? 😅

**Comment by JoeyStk** [comment]
@charludo Thank you very much for your feedback. All points should be addressed and included :) Can you please check if I missed anything?

Additionally I also added the redesign for the report list and the decline list. Therefore I think, if there is no big issue with it anymore, we push it today, so the testing can begin on Monday. I will add the new logo in a separate PR :)

**Review by charludo — APPROVED** [review]
> Therefore I think, if there is no big issue with it anymore, we push it today, so the testing can begin on Monday. 

Agreed! Again, thanks so much, this looks great!!

**Pull request merged**
